### ISSUE TITLE
Noise free feature

### ISSUE THREAD

**Issue by twomol** [GPUOpen-Effects/FidelityFX-FSR#15]
In FSR integration guide, it suggests FSR should be used before any effects introduce noise, if there is case I can't access engine source code, so  I cant avoid this.  Is there any idea or direction to investigate to apply FSR on the final image which has noise effect?

**Comment by twomol** [comment]
More comments: Why FSR suggest FSR pass should be befind any effects that introduce noise, I have do some experiments doing FSR on FilmGrain and Chromatic Aberration effects images, looks it works good

**Comment by rys** [comment]
FSR's algorithm can potentially exacerbate high frequency input, which is why we recommend anti-aliased input to the system. Ultimately it's content dependent, like all scalers, so you might have good results depending on what you're asking it to scale. If you don't have engine source code then experimenting with placing it at different parts of a renderer to try are much more difficult sadly. The best FSR integrations will always be those that can be done at the right spot in a render pipe.

**Comment by twomol** [comment]
"FSR's algorithm can potentially exacerbate high frequency input"
So does the following steps theoretically help:
1. Apply Fourier Transform on the target to remove high frequency part
2. Apply FSR
3. put  high frequency part back to the target
